# Generated by Django 4.0.6 on 2022-09-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0004_alter_photo_people_remove_photo_year_photo_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
    ]
