# Generated by Django 4.0.6 on 2022-09-15 02:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_alter_year_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[360, 360], upload_to='thumbnails/'),
        ),
    ]
