# Generated by Django 5.2.5 on 2025-08-13 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0010_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoapp.year'),
        ),
    ]
