# Generated by Django 5.2.5 on 2025-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_temp_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_pwd',
        ),
        migrations.AddField(
            model_name='user',
            name='tmp_pwd',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='tmp_pwd_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tmp_pwd_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
